services:
  flipper:
    container_name: flipper
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        FLIPPER_UID: "${FLIPPER_UID:-missing}"
        FLIPPER_GID: "${FLIPPER_GID:-missing}"
    image: flipper:latest
    hostname: flipper
    restart: unless-stopped
    stop_grace_period: 1m
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Above doesn't seem to work?? So using below:
    network_mode: host
    user: "${FLIPPER_UID:-missing}:${FLIPPER_GID:-missing}"
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: /home/otus/python/flipper/log/
        target: /app/log/
      - type: bind
        bind:
          create_host_path: false
        source: /home/otus/python/flipper/data/
        target: /app/data/
