services:
  flipper:
    container_name: flipper
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        FLIPPER_UID: "${FLIPPER_UID:-envmissing}"
        FLIPPER_GID: "${FLIPPER_GID:-envmissing}"
    image: "flipper:${IMAGE_TAG:-latest}"
    hostname: flipper
    restart: unless-stopped
    stop_grace_period: 1m
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Above doesn't seem to work?? So using below:
    network_mode: host
    user: "${FLIPPER_UID:-argmissing}:${FLIPPER_GID:-argmissing}"
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./log/
        target: /app/log/
      - type: bind
        bind:
          create_host_path: false
        source: ./data/
        target: /app/data/
